version: "3.7"

services:
  postgres:
    restart: unless-stopped
    image: postgres:14.2-alpine
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    build:
        context: .
    environment:
      - POSTGRES_USER=cacao
      - POSTGRES_PASSWORD=cacao_dao
      - POSTGRES_DB=cacao_dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cacao -d cacao_dev" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  postgres-data: